### ISSUE TITLE
 Could NOT find Boost (missing: Boost_INCLUDE_DIR) (Required is at least   version "1.48")

### ISSUE THREAD

**Issue by YZDYZDYZD** [tpms-lattice/ASLI#2]
I am trying to compile ASLI with cmake completely according to your user manual. But some issues still occured. 
When building ASLI in windows, the code "cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DMARCH_NATIVE=ON .. "  outputs "Could NOT find Boost (missing: Boost_INCLUDE_DIR) (Required is at least version "1.48")" every time.
I tried my best to fix these problem. Unfortunately I am still getting the same errors over and over again. 
Can anyone please help me handle these problem.
Thanks!

**Comment by tpms-lattice** [comment]
Its difficult to say were the issue may be with the information you have provided. A few things you may want to check are:
- Are you using MSYS2 MinGW x64? 
- Are you certain Boost is available on your system?
- Have you tried to specify Boost_INCLUDE_DIR manually?

If none of this helps, can you give some more details on what you did exactly and how did you try to fix it?
