### ISSUE TITLE
Can this software infill using any lattice other than TPMS lattices, such as body centered cubic?

### ISSUE THREAD

**Issue by CEBYMS** [tpms-lattice/ASLI#3]

**Comment by tpms-lattice** [comment]
Yes, it can generate any type of infill as long as you can provide it as a function and make the function triply periodic. In the case of the BCC it would come down to providing the function of the three cylinders that form them (rotated the at appropriate angles of each other), taking their union and repeating them with a shift to infinity.

**Comment by tpms-lattice** [comment]
A cubic unit cell has been added to [Infill.cpp](https://github.com/tpms-lattice/ASLI/blob/b6307c3a9e5c16181ce90f0b4531dbb60c2e3e11/src/Infill.cpp#L614-L636) that can serve as an example of how to make an otherwise non-periodic unit cell triply periodic.
