### ISSUE TITLE
Variable infill using FEA stresses capability ?

### ISSUE THREAD

**Issue by yvanblanchard** [tpms-lattice/ASLI#4]
Hello,

Could be nice to densify the infiller using stresses (from FEA calculations). 
Any extension like this planned at your side ? (or related work)

Anyway, thanks for sharing your very useful work!

**Comment by yvanblanchard** [comment]
Maybe it could be done through density input file ?

I see in the article the 'acetabular' test case: 
could you please share the model files ?
![image](https://user-images.githubusercontent.com/63931618/233772189-f35e5cae-2a6b-4711-a9ce-f92ad5ed4c39.png)

**Comment by tpms-lattice** [comment]
You can indeed use the undocumented feature I used to convert elastic moduli to volume fractions. To use it with your stresses as input you will need to save your stresses in a FAP file the same way you would if you were providing any other feature value. When doing so I would advice to keep the number of data points limited as it can slow down things dramatically if you have a larger mesh and were to pass on data points for all the nodes.
In the code itself you will have to add your stress conversion function to the internal function eModulus2vFraction() found in [infill.cpp](https://github.com/tpms-lattice/ASLI/blob/b6307c3a9e5c16181ce90f0b4531dbb60c2e3e11/src/Infill.cpp#L509-L547)

To do so add another else if clause to the if statement:
```
else if (materialParameters.materialModel == "stresses") 
{
// Function converting stresses into volume fractions
// return the volume fraction computed by the function above
}
```
Place your own function inside it and return its output. The stress values you provide through the FAP file will be found in the variable materialParameters.eModulusSolid. Once you have recompiled the code you just need to specify elasticModulus in lt_feature and stresses under mp_materialModel.

When I have some time I will change this to be a 'general user defined input' and document it. The functionality and changes required will remain unchanged though.

**Comment by yvanblanchard** [comment]
OK, thanks.
Could you please provide a set of sample files (acetabular model ? with FAP file), illustrating this particular usage ?
Thank you again.

**Comment by tpms-lattice** [comment]
I have generalized the `eModulus2vFraction()` function which is now called [`userDefinedInput2vFraction()`](https://github.com/tpms-lattice/ASLI/blob/1bda196ec8e499ba8788ca6573e9b2cdff0f9cbf/src/Infill.cpp#L509-L556). It now also includes the else if statement for [stresses](https://github.com/tpms-lattice/ASLI/blob/1bda196ec8e499ba8788ca6573e9b2cdff0f9cbf/src/Infill.cpp#L548-L550) were you only need to replace the two lines  currently present in it by your own code. For the time being I think I will leave it as an undocumented option though.
As for the files of the cup, these are based on the results of another project we are still working on and for which we still have to publish the results. Until we do so I cannot share those files. You can use the example file I uploaded in the link bellow in combination with the sample cube that comes with the code if you want to test the user defined feature option with a trivial elastic modulus conversion example. You will see it's exactly the same as any other FAP file but with values of a different magnitude that end up being converted by `userDefinedInput2vFraction()` into a value between 0 and 1. To use it with the current master branch simply download the FAP file, place it in the inputs folder found in the bin folder after compiling the source code and set `fap` to `inputs/cube_elasticModulus.fap`, `lt_feature` to `userDefined` and `lt_feature_val` to `0`. When you run ASLI you should now get a graded cube based on the elastic modulus specified in the FAP file.

[cube_elasticModulus.fap](https://we.tl/t-tDBhsaeYN7) 

Hope the sample file helps illustrate the usage.
