### ISSUE TITLE
How to run ASLI through C++

### ISSUE THREAD

**Issue by ayushi-iitkgp** [tpms-lattice/ASLI#6]
I have used QASLI as well as ASLI using the command prompt, but I've never used it by running the .cpp files. Could you please help with this?
I would like to run Infill.cpp to create a custom unit cell which is non-periodic and infill a model with that.

**Comment by tpms-lattice** [comment]
You can't just run c++ source files. You need to build the source code (compile and link) in order to obtain an executable file you can then run. You can find the steps to build ASLI described in both the readme file and the manual accompanying the source code.
