### ISSUE TITLE
Possible to use infill bars/cylinders as unit cell ?

### ISSUE THREAD

**Issue by yvanblanchard** [tpms-lattice/ASLI#8]
Hello
I was wondering if we could use simple connected cylinders as unit cell for infill (not Tpms), since it is easy to model with implicit function ?

thank you

![image](https://github.com/tpms-lattice/ASLI/assets/63931618/72bba302-9d18-4eff-81d7-671db3897187)

**Comment by tpms-lattice** [comment]
Yes, it is possible and fairly straightforward. If you have a look at the (undocumented) [“cubic”](https://github.com/tpms-lattice/ASLI/blob/1bda196ec8e499ba8788ca6573e9b2cdff0f9cbf/src/Infill.cpp?plain=#L624-L644) unit cell in the infill.cpp file you will find an example of a unit cell created making use of implicit functions of cylinders.

**Comment by yvanblanchard** [comment]
Very well, thank you!
It would be interesting to store/export the result (cylinders) in a 3MF format with Beams modeling extension (for performances).
I will try that.
