### ISSUE TITLE
Output result file format

### ISSUE THREAD

**Issue by virtuamechanica** [tpms-lattice/ASLI#9]
Hello
Could you please tell me which kind of format is the output result file ?
I was just wondering how to use it for explicit meshing for FEA.
Which software did you used for producing the pictures from the user manual pdf ?

Thank you

**Comment by tpms-lattice** [comment]
- Surface triangulations are saved in the [stereolithography file format](https://www.fabbers.com/tech/STL_Format) (.stl extension) and volume meshes in the [medit file format](https://hal.inria.fr/inria-00069921/document) (.mesh extension).
- If your FEA software cannot import the format you can convert to a compatible format using external tools like [Gmsh](https://gmsh.info/) or [meshio](https://pypi.org/project/meshio/).
- I assume you refer to the images in Fig. 4 and 5. These images were generated using [blender](https://www.blender.org).
